### ISSUE TITLE
Screenshot/Usage Example

### ISSUE THREAD

**Issue by kahlil29** [mvegter/openapi-diff-action#1]
This looks interesting but I'm fairly new to GitHub Actions so I'm not sure if I should be adding this to my repository or not. 
My repository contains just a single OpenAPI yaml file so I think it does fit the use-case, but I would just like to be sure. 

I'll probably set up a test repository and try out the `Action` on that, if all goes well, would you be okay with me raising a PR to update the README with a screenshot(s) ?

**Comment by mvegter** [comment]
@kahlil29 feel free to open a PR, I would be more than happy to merge it. I added an example of how to use it in the README.md, if anything is unclear let me know.

**Comment by kahlil29** [comment]
Thanks for the prompt reply @mvegter 
I'll get back to you once I've tried it out 👍
